# https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions

- apt_repository:
    repo: "{{ item.config }}"
    state: present
    filename: "{{ item.name }}.list"
  when: item.config is defined and item.name is defined
  register: changed

- apt_key:
    url: "{{ item.key }}"
    state: present
  when: changed and item.key is defined

- apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.keyid }}"
    state: present
  when: changed and item.keyserver is defined and item.keyid is defined
  
        